name: Deploy to Cloudflare Pages

on:
  workflow_call:
    inputs:
      website:
        required: true
        type: string
        description: 'Site name to deploy'
      deploy-to-production:
        required: true
        type: boolean
        description: 'Whether to deploy to production (main branch) or preview'
    secrets:
      cloudflare-api-token:
        required: true
        description: 'Cloudflare API Token'
      cloudflare-account-id:
        required: true
        description: 'Cloudflare Account ID'

jobs:
  build:
    runs-on: macos-15
    env:
      DEVELOPER_DIR: "/Applications/Xcode_16.4.app/Contents/Developer"
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache Swift Package Manager
        uses: actions/cache@v3
        with:
          path: |
            .build
            ~/.cache/org.swift.swiftpm
          key: ${{ runner.os }}-spm-${{ hashFiles('Package.swift', 'Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-

      - name: Build Dependencies
        run: swift build --configuration release

      - name: Run Tests
        run: swift test --parallel

      - name: Generate Site
        run: swift run ${{ inputs.website }}

      - name: Compile Tailwind CSS
        run: |
          website="${{ inputs.website }}"
          config_file="Resources/${website}/tailwind.config.cjs"
          
          # Find all CSS input files using the flexible pattern
          css_files=$(find "Resources/${website}" -name "style.input.css" -path "*/static/style.input.css" 2>/dev/null || true)
          
          if [ -z "$css_files" ]; then
            echo "Error: No CSS input files found in Resources/${website}"
            echo "Expected pattern: Resources/${website}/*/static/style.input.css"
            exit 1
          fi
          
          echo "Found CSS input files:"
          echo "$css_files"
          
          # Compile each CSS file
          while IFS= read -r input_file; do
            # Extract the page path from the input file
            # e.g., Resources/21-dev/static/style.input.css -> static
            # e.g., Resources/21-dev/p256k/static/style.input.css -> p256k/static
            relative_path=$(echo "$input_file" | sed "s|Resources/${website}/||" | sed 's|/style\.input\.css$||')
            
            if [ "$relative_path" = "static" ]; then
              # Root CSS file
              output_file="Websites/${website}/static/style.css"
              echo "Compiling root CSS: $input_file -> $output_file"
            else
              # Page-specific CSS file
              output_file="Websites/${website}/${relative_path}/style.css"
              echo "Compiling page CSS: $input_file -> $output_file"
              
              # Ensure output directory exists
              mkdir -p "$(dirname "$output_file")"
            fi
            
            # Compile the CSS file
            if ! swift package --disable-sandbox tailwindcss \
              --input "$input_file" \
              --output "$output_file" \
              --config "$config_file"; then
              echo "Error: Failed to compile $input_file"
              exit 1
            fi
            
            echo "Successfully compiled: $output_file"
          done <<< "$css_files"

      - name: Verify Build Output
        run: |
          website="${{ inputs.website }}"
          echo "Checking build output..."
          ls -la Websites/${website}/
          
          # Verify index.html exists
          if [ ! -f "Websites/${website}/index.html" ]; then
            echo "Error: index.html not found in build output"
            exit 1
          fi
          
          # Verify CSS files exist - check for compiled CSS files
          css_found=false
          
          # Look for any compiled CSS files that should exist
          if find "Websites/${website}" -name "style.css" -path "*/static/style.css" | grep -q .; then
            css_found=true
            echo "Found compiled CSS files:"
            find "Websites/${website}" -name "style.css" -path "*/static/style.css"
          fi
          
          if [ "$css_found" = false ]; then
            echo "Error: No compiled CSS files found in build output"
            echo "Expected at least one file matching: Websites/${website}/*/static/style.css"
            exit 1
          fi
          
          echo "Build output verified successfully"

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.website }}-build
          path: Websites/${{ inputs.website }}/
          retention-days: 1

  deploy:
    needs: build
    runs-on: ubuntu-latest
    env:
      DEPLOYMENT_BRANCH: preview
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: read
      deployments: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check for Production Deployment
        run: |
          if [[ ${{ inputs.deploy-to-production }} == true ]]; then
            echo "DEPLOYMENT_BRANCH=main" >> $GITHUB_ENV
          fi

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.website }}-build
          path: Websites/${{ inputs.website }}

      - name: Publish to Cloudflare Pages
        id: cloudflare
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.cloudflare-api-token }}
          accountId: ${{ secrets.cloudflare-account-id }}
          projectName: ${{ inputs.website }}
          directory: Websites/${{ inputs.website }}
          branch: ${{ env.DEPLOYMENT_BRANCH }}
          wranglerVersion: '3'

      - name: Prepare comment body
        if: github.event_name == 'pull_request'
        id: format-output
        run: |
          if [ "${{ steps.cloudflare.outcome }}" == "failure" ]; then
            DEPLOYMENT_STATUS="❌ Deployment Failed!"
          else
            DEPLOYMENT_STATUS="✅ Deployment Successful!"
          fi

          echo "DEPLOYMENT_TEXT<<EOF" >> $GITHUB_ENV
          echo "### Deploying Preview for ${{ inputs.website }} 🚀" >> $GITHUB_ENV
          echo "---" >> $GITHUB_ENV
          echo "| **Name** | **Result** |" >> $GITHUB_ENV
          echo "|---------------------------------|------------------------|" >> $GITHUB_ENV
          echo "|🔀 Latest Commit | ${{ github.sha }} |" >> $GITHUB_ENV
          echo "|🛰️ Status | $DEPLOYMENT_STATUS |" >> $GITHUB_ENV
          echo "|🪵 Action Run | [View Logs](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}) |" >> $GITHUB_ENV
          echo "|🔍 Preview Url | [${{ steps.cloudflare.outputs.url }}](${{ steps.cloudflare.outputs.url }}) |" >> $GITHUB_ENV
          echo "|🕵🏻‍♂️ Alias Url | [${{ steps.cloudflare.outputs.alias }}](${{ steps.cloudflare.outputs.alias }}) |" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Deployment Preview Comment
        if: github.event_name == 'pull_request'
        run: |
          # Try to edit last comment, fallback to creating new comment if none exists
          if ! gh issue comment ${{ github.event.pull_request.number }} --edit-last --body "${{ env.DEPLOYMENT_TEXT }}" 2>/dev/null; then
            echo "No previous comment found, creating new comment..."
            gh issue comment ${{ github.event.pull_request.number }} --body "${{ env.DEPLOYMENT_TEXT }}"
          fi
